#!/bin/bash
set -e

if [[ "$SKYWALKING_ENABLED" = true ]]; then
	if [[ $SKYWALKING_JAVAAGENT ]]; then
		SKYWALKING_OPS="-javaagent:$SKYWALKING_JAVAAGENT"
	fi
	if [[ $SKYWALKING_AGENTCOLLECTOR_BACKEND_SERVICE_APPLICATION_CODE ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.application_code=$SKYWALKING_AGENTCOLLECTOR_BACKEND_SERVICE_APPLICATION_CODE"
	fi
	if [[ $SKYWALKING_AGENT_NAMESPACE ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.namespace=$SKYWALKING_AGENT_NAMESPACE"
	fi
	if [[ $SKYWALKING_AGENT_SAMPLE_N_PER_3_SECS ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.sample_n_per_3_secs=$SKYWALKING_AGENT_SAMPLE_N_PER_3_SECS"
	fi
	if [[ $SKYWALKING_AGENT_AUTHENTICATION ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.authentication=$SKYWALKING_AGENT_AUTHENTICATION"
	fi
	if [[ $SKYWALKING_AGENT_SPAN_LIMIT_PER_SEGMENT ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.span_limit_per_segment=$SKYWALKING_AGENT_SPAN_LIMIT_PER_SEGMENT"
	fi
	if [[ $SKYWALKING_AGENT_IGNORE_SUFFIX ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.ignore_suffix=$SKYWALKING_AGENT_IGNORE_SUFFIX"
	fi
	if [[ $SKYWALKING_AGENT_IS_OPEN_DEBUGGING_CLASS ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.agent.is_open_debugging_class=$SKYWALKING_AGENT_IS_OPEN_DEBUGGING_CLASS"
	fi
	if [[ $SKYWALKING_COLLECTOR_BACKEND_SERVICE ]]; then
		SKYWALKING_OPS="$SKYWALKING_OPS -Dskywalking.collector.backend_service=$SKYWALKING_COLLECTOR_BACKEND_SERVICE"
	fi
fi

exec java $JAVA_OPTS $SKYWALKING_OPS -jar /api-gateway.jar